import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

import Header from '@/features/navigation/ui/Header'

import '@/shared/styles/globals.css'

import { container } from '../../styled-system/patterns'

const roboto = Montserrat({
	variable: '--font-montserrat',
	subsets: ['cyrillic']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${roboto.variable}`}>
				<div className={container()}>
					<Header />
					<main>{children}</main>
				</div>
			</body>
		</html>
	)
}
